### ISSUE TITLE
The devfile schema/samples should have version and name

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#10]
Adding optional metadata `version` and `generatedName`:

```yaml
schemaVersion: 2.0.0
metadata:
  name: petclinic-dev-environment                # optional
  version: x.y.z                                          # optional
projects:
   ...
components:
  ...
commands:
  ...
```

Since in the schema the metadata are optional they can even be extracted in a meta.yaml as it is today in the devfile-registry but that's not covered in the spec.

⚠️ That's about the version of the devfile and not to be confused with the `schemaVersion`. And the semantic is the semVer one.
