### ISSUE TITLE
Manage merge keys of top-level lists in a more consistent way

### ISSUE THREAD

**Issue by davidfestal** [devfile/kubernetes-api#102]
In the current model, all types of commands are expected to have an `id` that is mainly the key of the command in the command list.

It is defined this way:

```yaml
commands:
  - exec:
      id: "commandId"  <------ the key of the given command in the list of commands 
```

Since finally the `id` field is common to all types of command and is the key that will be used to identify a command especially while merge commands between a parent and the current devfile, it seems it might make sense to bring it one level up, like this:

```yaml
commands:
  - id: "commandId"
    exec:
      ....
```

The same stands for components: until now all types of components have a `name` field that is used as a key for identifying a component, especially during parent or plugin overriding. It is mandatory for most component types, and optional for plugins, in which case it is calculated from the definition of the plugin itself (based on id, registry url, etc ...).

Instead of: 
```yaml
components:
  - container:
      name: "tooling"
```
we would have
```yaml
components:
  - name: "tooling"
    container:
      ....
```
In this case, though, the `name` field can only be made either required or optional for all the component types, and not per-component-type. We should then probably make it mandatory for the Kubernetes CR, and optional for devfiles (but for all components). We would still loose some schema validation.
Of course, deciding that in any case we require a `name` for a component (even a plugin) would make the whole more consistent and schema-validated, but less user-friendly I admit.

So that this requires further discussion.

Related content: https://github.com/devfile/kubernetes-api/pull/98#user-content-keys

**Comment by kadel** [comment]
> In this case, though, _the `name` field can only be made either required or optional for all the component types, and not per-component-type_. We should then probably make it mandatory for the Kubernetes CR, and optional for devfiles (but for all components). This would lead to loosing some schema validation.

> Of course, deciding that in any case we require a `name` for a component (even a plugin) would make the whole more consistent and schema-validated, but less user-friendly I admit.

I think that might make it confusing. If there any other disadvantage in making it required for devfiles?
I would say that consistency would make it more user-friendly.

**Comment by davidfestal** [comment]
> One downside that I can see in this is that it would make it syntactically possible to define multiple components or command under one name :-( I'm not sure if we can check for this on JSON Schema level

It is not possible, in fact, since `exec` / `apply` are part of a union. In each case a K8S unions is used, the json schema generation process adds a `oneOf` schema constraint in the json schema, that validates that only one of the various union members (here `apply` or `exec`) is provided.

It's already working like that in other places where unions are used: project source (`git`, `zip`), which is besides the project `name` and the `clonePath` for example.

> Is there any other disadvantage in making it required for devfiles?
> I would say that consistency would make it more user-friendly.

The question is mainly that, until now, we had said that `plugin`s should not require the use of a name, since the plugin component `name` (sort of "key") can be deduced from the plugin `id` or  `uri`.
So that's more question for @l0rd

**Comment by amisevsk** [comment]
One issue I have with the proposed change is that separating `name` or `id` in this way looks cleaner when we type it out, but often yaml keys will be reorganized at some point in the serialization-deserialization-format chain. The example below is harder to read, in my opinion (though the same problem exists regardless of where we put `name`)

<details>
<summary>devfile.yaml</summary>

```yaml
schemaVersion: 2.0.0
metadata:
  name: java-quarkus
  version: 1.0.0
  website: https://quarkus.io
projects:
  - name: quarkus-ex
    git:
      location: https://github.com/odo-devfiles/quarkus-ex
components:
  - container:
      image: quay.io/eclipse/che-quarkus:nightly
      memoryLimit: 1512Mi
      mountSources: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      endpoints:
        - name: '8080/http'
          targetPort: 8080
    name: tools
  - volume:
      size: 3Gi
    name: m2
commands:
  - exec:
      component: tools
      commandLine: "mvn compile"
      workingDir: $PROJECTS_ROOT/quarkus-ex
    id: init-compile
  - exec:
      component: tools
      commandLine: "mvn quarkus:dev"
      attributes:
          restart: "false"
      group:
        kind: run
        isDefault: true
      workingDir: $PROJECTS_ROOT/quarkus-ex
    id: dev-run
events:
  postStart:
    - init-compile
```

</details>

I pretty consistently have this reorganzation problem when looking at devfiles in current Eclipse Che, for example:

<details>
<summary>Snippet of one of my devfiles (1.0 spec)</summary>

```yaml
  - mountSources: true
    endpoints:
      - name: che-docs-livereload-server
        port: 35729
      - name: che-docs-web-server
        port: 4000
        attributes:
          path: /che-7/introduction-to-eclipse-che/
    args:
      - sleep
      - infinity
    memoryLimit: 1Gi
    type: dockerimage
    image: 'docker.io/amisevsk/che-docs-dev:latest'
    alias: che-docs-dev
```

</details>

(though here all keys are at the same level
