### ISSUE TITLE
Find a better naming for chePlugin spec reference

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#13]
Currently the following syntax are used to reference the spec in a che-plugin registry or in a yaml file published on the internet respectively:

```yaml
components:
  - chePlugin:
      registry:
        id: redhat/vscode-yaml/latest
        registryUrl: "external-registry-url"
  - chePlugin:
      url: https://gist.../meta.yaml
```

That may be confusing. We should find a better name.

**Comment by davidfestal** [comment]
In the PR https://github.com/che-incubator/devworkspace-api/pull/29, that introduces changes agreed on in issue #25, I included the following proposal which would also be useful to reference a parent devfile inside a devfile registry:

```yaml
components:
  - chePlugin:
      registryEntry:
        id: redhat/vscode-yaml/latest
        baseUrl: "external-registry-url"
  - chePlugin:
      url: https://gist.../meta.yaml
```

To be fully consistent with the [`parent` case](https://github.com/che-incubator/devworkspace-api/issues/25), we could use `uri` instead of `url` when pointing directly to a plugin `meta.yaml`
