### ISSUE TITLE
Allow the size of a component's volume to be specified in a Devfile

### ISSUE THREAD

**Issue by johnmcollier** [devfile/kubernetes-api#14]
Right now, there isn’t a way to specify the size of a component’s volume in a devfile, and Che will use the size specified in che.properties (default 1Gi). As different component-types may have different volume requirements (e.g. the issue seen in https://github.com/openshift/odo/issues/2455), Odo will have a need to specify the size of volumes it interacts with, and rather than having an odo-specific setting, it would be nice if we could store this setting in the devfile, 

This change might also be nice for Che, as it would allow components to configure the size of volumes they need (such as a maven cache volume that requires more than 1Gi), rather than relying on global Che defaults.

Something like:

```yaml
---
components:
  - container:
      image: "maven"
      name: "maven"
      volumesMount: 
      - name: my-data-volume
  - volume:
     name: my-data-volume
     size: 5Gi
```
