### ISSUE TITLE
Composite commands label and id

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#18]
Composite currently only has a `label`. But that appears to be something that would be visible in the Che UI. It should have an `id` as well so that tools like odo can reference composite commands with the following requirements:

- 2 distincts attributes: `label` and `id` 
- both can coexist
- `id` is mandatory
- `id` used to reference parent devfiles commands (not `label`)

Sample devfile snippet to show example of usage/format:

```yaml
projects:
 - name: "devworkspace-spec"
   git:
       location: "https://github.com/che-incubator/devworkspace-api"
       branch: "master"
commands:
 - exec:
     commandLine: "./buildSchema.sh"
     component: build-tools
     id: buildSchema
 - vscodeTask:
     id: openDevfile
     inlined:
       json       
 - composite:
     id: buildAndOpen
     label: Build schema and open devfile
     commands:
       - buildSchema
       - openDevfile
     parallel: false
components:
 - container:
     image: some container image with required build tools
     name: "build-tools"
```

**Comment by l0rd** [comment]
cc @johnmcollier @elsony

**Comment by l0rd** [comment]
Agreement: 2 attributes, `label` and `id` and at least one of those 2 should be present.

**Comment by groeges** [comment]
@l0rd Looking at this issue alongside https://github.com/che-incubator/devworkspace-api/issues/27 will the composite element define the group or will each of the individual exec elements define a group. My thoughts are the composite would define the group but wanted to check.

**Comment by l0rd** [comment]
@groeges I would say that the group can be specified for a composite and its commands can belong to distinct groups:

```yaml
commands:
 - exec:
     id: build
     commandLine: "./build.sh"
     component: tooling
     group: 
        kind: build
 - exec:
     id: run
     commandLine: "./run.sh"
     component: tooling
     group: 
        kind: run
 - composite:
     id: buildAndRun
     label: Build and Run
     commands:
       - build
       - run
     parallel: false
     group: 
        kind: run
```
