### ISSUE TITLE
Allow volumes to be shared across components

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#19]
Odo will have a need for multiple components to mount the same volume. There isn’t an option in devfiles right now to define a volume once, and have multiple components mount that same volume. 

To work around this, we’re proposing adding a way to the devfile spec that allows you to define a volume once (a top level ‘volumes’ field), then easily add it to other components via a ‘volumeMount’ field. This is similar to how Kubernetes pods handle volumes.

Example:

```yaml
---
projects:
  - name: "my-project"
components:
  - container:
      image: "busybox"
      name: "mycontainer"
      memoryLimit: "128M"
      mountSources: true
      volumeMount:
        - name: my-data-volume
          path: /some/folder
  - kubernetes:
      referenceContent: |
        kind: Pod
        metadata:
          name: sample-pod
        spec:
          containers:
            image: docker.io/my-sample-image:latest
            volumeMounts:
            - mountPath: /some/path
              name: my-data-volume
  - volume:
     name: my-data-volume
     size: 5Gi
```

**Comment by l0rd** [comment]
cc @johnmcollier @elsony

**Comment by l0rd** [comment]
@johnmcollier will provide another example using a component of type Kubernetes

**Comment by sleshchenko** [comment]
Does it duplicate https://github.com/che-incubator/devworkspace-api/issues/16 ?

There is another interesting option to think about - add an ability to specify PVC name for volume https://github.com/eclipse/che/issues/15652

**Comment by johnmcollier** [comment]
@sleshchenko Yeah it's the same, since there's already some discussion here, I'll close out my issue in favour of this one.

**Comment by johnmcollier** [comment]
Sample with Kubernetes component:
```
---
projects:
  - name: "my-project"
components:
  - container:
      image: "busybox"
      name: "mycontainer"
      memoryLimit: "128M"
      mountSources: true
      volumeMount:
        - name: my-data-volume
          path: /some/folder
  - kubernetes:
      referenceContent: |
        kind: Pod
        metadata:
          name: sample-pod
        spec:
          containers:
            image: docker.io/my-sample-image:latest
            volumeMounts:
            - mountPath: /some/path
              name: my-data-volume
  - volume:
     name: my-data-volume
     size: 5Gi
```

In this scenario, the Kubernetes component references the `my-data-volume` defined in the `volume` section under components, rather than having to define one via a persistent volume claim in the pod spec.
