### ISSUE TITLE
Environment variables for a specific command

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#21]
Should it be possible to set environment variables that apply for a specific command? The current way to handle this would be to set the environment variables inline with the command but this can be cumbersome and reduce readability.

**Sample of current devfile snippet to show example of usage/format:**

```yaml
- exec:
     commandLine: "MAVEN_CONFIG=~/mvn/config JAVA_OPTS="-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
               -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
               -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
               -Duser.home=/home/user" ./buildSchema.sh"
     component: build-tools
     alias: buildSchema
```

**Example with proposed changes:**

```yaml
commands:
 - exec:
     commandLine: "./buildSchema.sh"
     env:
     - name: MAVEN_CONFIG
       value: "~/mvn/config"
     - name: JAVA_OPTS
       value: "-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
               -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
               -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
               -Duser.home=/home/user"
     component: build-tools
     alias: buildSchema
```
