### ISSUE TITLE
Renaming workdir into workingDir

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#22]
**Example with proposed changes:**

```yaml
commands:
 - exec:
     commandLine: "./buildSchema.sh"
     workingDir: "~/schemaScripts"
     component: build-tools
     alias: buildSchema
```

**Comment by l0rd** [comment]
cc @johnmcollier @elsony

**Comment by davidfestal** [comment]
There is already a `workDir` attribute for the `exec` commands in the current proposal on master.
But it was not mentioned in any samples.
Using it would be like that:

```yaml
  - exec:
      commandLine: "./buildSchema.sh"
      component: build-tools
      alias: buildSchema
      workdir: /projects/myProject
```

Of course the name can be changed if necessary.
