### ISSUE TITLE
starterProjects and projects description

### ISSUE THREAD

**Issue by neeraj-laad** [devfile/kubernetes-api#42]
In a devfile that is being used to define a stack, there could be multiple starter projects, each providing a separate starter application (simple app, app integrated with Kafka, reactive app etc.) 

Today we only have a `name` field to distinguish between them. But for developer to make a choice between these starter applications, having more details information on the capabilities you get with each project will be necessary.

If we can add `starterProjects` section, devfile creators will be able to use it for starter projects (only one should be selected by the user).

```yaml
starterProjects:
  - name: "kafka-project"
    description: "Use this app to get a nodejs application for working with kafka"
  - name: "simple-project"
    description: "Use this app to get a simple "hello world" nodejs application"
```

`starterProjects` would have the same syntax as `projects` but a slightly different behavior: instead of cloning the git repo, only the source code would be fetched, the git metadata would not.

Moreover we would like to add the `description` field to both `project` and `starterProject` to help developers understand the content of the project.

**Comment by l0rd** [comment]
Alternative 1: using 2 devfiles that reference the same parent devfile:

```yaml
projects:
  - name: "kafka-project"
    description: "Use this app to get a nodejs application for working with kafka"
parent:
  - id: nodejs-stack
```

```yaml
projects:
  - name: "simple-project"
    description: "Use this app to get a simple "hello world" nodejs application"
parent:
  - id: nodejs-stack
```

Alternative 2: using `starterProjectOnly` field only:

```yaml
projects:
  - name: "kafka-project"
    description: "Use this app to get a nodejs application for working with kafka"
    starterProjectOnly: true
  - name: "simple-project"
    description: "Use this app to get a simple "hello world" nodejs application"
```
