### ISSUE TITLE
Improve devworkspace status

### ISSUE THREAD

**Issue by amisevsk** [devfile/kubernetes-api#44]
The devworkspace status field is currently lacking for many use cases. I'd like to propose adding a few fields that are common to other k8s objects in order to support management better.

New fields:
- `.status.conditions` - Type `corev1.Condition[]`, stores information about various aspects of workspace state (c.f. `.status.conditions` on Pods.)
- `.status.phase` - String valued, stores current "phase" of workspace (e.g. `running`, `started`, `stopped`, `failed`)

The struct for conditions would be the common Kubernetes condition struct type.

### Use cases
Conditions can be used to share information about progress in a workspace start process -- e.g. "storage ready", "deployment created", "deployment ready". They can also be used to give more detailed information about the last observed state of a workspace (e.g. the workspace deployment isn't ready because we're pulling images)

Phase is useful to track the status of the workspace -- if e.g. a routing class that is unsupported is specified, a workspace can be marked as "failed". If another service is waiting to show `mainIdeUrl` to the user, it needs to know the workspace is in a running state.

### Proposal
```yaml
status:
  condition:
  - lastTransitionTime: "2020-05-06T23:21:55Z"
    status: "True"
    type: ServiceAccountReady
  - lastTransitionTime: "2020-05-06T23:21:55Z"
    status: "True"
    type: RoutingReady
  - lastTransitionTime: "2020-05-06T23:21:55Z"
    status: "True"
    type: DeploymentReady
    reason: "OneWordReasonForTransition"
    message: "User-readable message about transition"
  - lastTransitionTime: "2020-05-06T23:21:55Z"
    status: "True"
    type: ComponentsReady
  phase: Running
  mainIdeUrl: https://my-workspace.my-cluster.com
  workspaceId: workspace-id
  additionalInfo: {}
```

Supported Phases:
- `Running`: Workspace is fully operational and can be accessed
- `Starting`: Workspace is currently being started
- `Stopped`: Workspace exists but is not running
- `Stopping`: Workspace is currently stopping (potentially waiting on preStop actions, e.g.
- `Failed`: There is an issue preventing this workspace from entering the `Running` phase.

For conditions, I don't have a concrete proposal for categories. Currently, in the che-workspace-operator (which would adopt this API), we use 
```go
const (
	WorkspaceComponentsReady     WorkspaceConditionType = "ComponentsReady"
	WorkspaceRoutingReady        WorkspaceConditionType = "RoutingReady"
	WorkspaceServiceAccountReady WorkspaceConditionType = "ServiceAccountReady"
	WorkspaceDeploymentReady     WorkspaceConditionType = "DeploymentReady"
)
```
but I don't view this list as complete.
