### ISSUE TITLE
Out of main pod containers

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#48]
In current devfile spec there it is not possible to specify if a container will be run as part of the main dev environment pod[1] or if it should run in its own separated pod. In the v2.0.0 spec we would like to add a new field (`dedicatedPod `) that can be applied to container components.

```yaml
components:
  - container:
        image: maven
        dedicatedPod: true          # <-- Optional. Default value is false
```

[1] In Che the main pod is the pod where the editor and its plugins run.

**Comment by benoitf** [comment]
hi, in the comment there is a typo on "runIsnOwnPod" (is/in)

alternatives could it be like `dedicatedPod: true` or `separatePod: true`

**Comment by l0rd** [comment]
@benoitf thanks. Changed to `dedicatedPod: true`.

**Comment by metlos** [comment]
I think we should be careful with the endpoint definitions (#33).

If the default endpoint exposure is `none` (which is fine for single-pod workspaces), the following would IMHO be slightly hard to decipher to the user:

```
components:
  - container:
        image: postgresql
        dedicatedPod: true
        endpoints:
        - name: dbPort
          targetPort: 5432
```

This definition would make the endpoint unreachable from the rest of the workspace (default exposure is `none`).
