### ISSUE TITLE
Rename command group type

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/kubernetes-api#59]
As odo is working on consuming the v2 spec, i noticed that the command group kind is called command group type https://github.com/devfile/kubernetes-api/blob/master/pkg/apis/workspaces/v1alpha1/commands.go#L20
```
// CommandGroupType describes the kind of command group.
// +kubebuilder:validation:Enum=build;run;test;debug
type CommandGroupType string
```

Can we please rename this to `CommandGroupKind` to be consistent with the discussion here in https://github.com/devfile/kubernetes-api/issues/27 and also devfile actually uses `kind` instead of `type`:
```
commands:
  - exec:
      id: devBuild
      component: runtime
      commandLine: npm install
      workingDir: ${CHE_PROJECTS_ROOT}/nodejs-web-app/app
      group:
        kind: build
        isDefault: true
```
