### ISSUE TITLE
Renaming dockerimage component type

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#8]
The new type is `container`:

```yaml
components:
  - container:
      image: busybox
      endpoints:
        - name: petclinic-web-server
```

 Possible alternative may be `image`, `containerImage` or `ociImage`...
