### ISSUE TITLE
Names field mandatory for k8s/openshift, optional for plugins

### ISSUE THREAD

**Issue by l0rd** [devfile/kubernetes-api#9]
- `alias` should not be used anymore
- `name` should be mandatory for kubernetes/openshift/containers components
- `name` should be optional for plugins components
- If `name` is not specified for a component of type plugin it should be inferred from its `id`/`url` field (`id`/`url` are used as `name` if its not specified explicitly) 

```yaml
### a Devfile spec

- container:
     name: tooling-container # <-- mandatory
     image: busybox
     mountSources: true
     endpoints:
       - name: petclinic-web-server

- kubernetes:
     name: mongodb # <-- mandatory
     reference: .../deployment.yaml # <-- already have a metadata.name: 'database1'

- plugin:
     name: vscode-java # <-- optional
     id: ms-vscode/vscode-java/1.1.1
```
